#!/usr/bin/env python3

import sys

rtable = "[bcdfghjklmnpqrstvwxyz][aeiou]"

table1={"ba": "B",
        "be": "[b]b[/b]",
        "bi": "[i]b[/i]",
        "bu": "[u]b[/u]",
        "by": "[i]b[/i]",
        "ca": "C",
        "ce": "[b]c[/b]",
        "ci": "[i]c[/i]",
        "cu": "[u]c[/u]",
        "cy": "[i]c[/i]",
        "da": "D",
        "de": "[b]d[/b]",
        "di": "[i]d[/i]",
        "du": "[u]d[/u]",
        "dy": "[i]d[/i]",
        "fa": "F",
        "fe": "[b]f[/b]",
        "fi": "[i]f[/i]",
        "fu": "[u]f[/u]",
        "fy": "[i]f[/i]",
        "ga": "G",
        "ge": "[b]g[/b]",
        "gi": "[i]g[/i]",
        "gu": "[u]g[/u]",
        "gy": "[i]g[/i]",
        "ha": "H",
        "he": "[b]h[/b]",
        "hi": "[i]h[/i]",
        "hu": "[u]h[/u]",
        "hy": "[i]h[/i]",
        "ja": "J",
        "je": "[b]j[/b]",
        "ji": "[i]j[/i]",
        "ju": "[u]j[/u]",
        "jy": "[i]j[/i]",
        "ka": "K",
        "ke": "[b]k[/b]",
        "ki": "[i]k[/i]",
        "ku": "[u]k[/u]",
        "ky": "[i]k[/i]",
        "la": "L",
        "le": "[b]l[/b]",
        "li": "[i]l[/i]",
        "lu": "[u]l[/u]",
        "ly": "[i]l[/i]",
        "ma": "M",
        "me": "[b]m[/b]",
        "mi": "[i]m[/i]",
        "mu": "[u]m[/u]",
        "my": "[i]m[/i]",
        "na": "N",
        "ne": "[b]n[/b]",
        "ni": "[i]n[/i]",
        "nu": "[u]n[/u]",
        "ny": "[i]n[/i]",
        "pa": "P",
        "pe": "[b]p[/b]",
        "pi": "[i]p[/i]",
        "pu": "[u]p[/u]",
        "py": "[i]p[/i]",
        "qa": "Q",
        "qe": "[b]q[/b]",
        "qi": "[i]q[/i]",
        "qu": "[u]q[/u]",
        "qy": "[i]q[/i]",
        "ra": "R",
        "re": "[b]r[/b]",
        "ri": "[i]r[/i]",
        "ru": "[u]r[/u]",
        "ry": "[i]r[/i]",
        "sa": "S",
        "se": "[b]s[/b]",
        "si": "[i]s[/i]",
        "su": "[u]s[/u]",
        "sy": "[i]s[/i]",
        "ta": "T",
        "te": "[b]t[/b]",
        "ti": "[i]t[/i]",
        "tu": "[u]t[/u]",
        "ty": "[i]t[/i]",
        "va": "V",
        "ve": "[b]v[/b]",
        "vi": "[i]v[/i]",
        "vu": "[u]v[/u]",
        "vy": "[i]v[/i]",
        "wa": "W",
        "we": "[b]w[/b]",
        "wi": "[i]w[/i]",
        "wu": "[u]w[/u]",
        "wy": "[i]w[/i]",
        "xa": "X",
        "xe": "[b]x[/b]",
        "xi": "[i]x[/i]",
        "xu": "[u]x[/u]",
        "xy": "[i]x[/i]",
        "ya": "Y",
        "ye": "[b]y[/b]",
        "yi": "[i]y[/i]",
        "yu": "[u]y[/u]",
        "yy": "[i]y[/i]",
        "za": "Z",
        "ze": "[b]z[/b]",
        "zi": "[i]z[/i]",
        "zu": "[u]z[/u]",
        "zy": "[i]z[/i]"}

table2={"bo": "[s]b[/s]",
        "co": "[s]c[/s]",
        "do": "[s]d[/s]",
        "fo": "[s]f[/s]",
        "go": "[s]g[/s]",
        "ho": "[s]h[/s]",
        "jo": "[s]j[/s]",
        "ko": "[s]k[/s]",
        "lo": "[s]l[/s]",
        "mo": "[s]m[/s]",
        "no": "[s]n[/s]",
        "po": "[s]p[/s]",
        "qo": "[s]q[/s]",
        "ro": "[s]r[/s]",
        "so": "[s]s[/s]",
        "to": "[s]t[/s]",
        "vo": "[s]v[/s]",
        "wo": "[s]w[/s]",
        "xo": "[s]x[/s]",
        "yo": "[s]y[/s]",
        "zo": "[s]z[/s]"}

table3={"ab": "°B",
        "eb": "[b]°b[/b]",
        "ib": "[i]°b[/i]",
        "ub": "[u]°b[/u]",
        "yb": "[i]°b[/i]",
        "ac": "°C",
        "ec": "[b]°c[/b]",
        "ic": "[i]°c[/i]",
        "uc": "[u]°c[/u]",
        "yc": "[i]°c[/i]",
        "ad": "°D",
        "ed": "[b]°d[/b]",
        "id": "[i]°d[/i]",
        "ud": "[u]°d[/u]",
        "yd": "[i]°d[/i]",
        "af": "°F",
        "ef": "[b]°f[/b]",
        "if": "[i]°f[/i]",
        "uf": "[u]°f[/u]",
        "yf": "[i]°f[/i]",
        "ag": "°G",
        "eg": "[b]°g[/b]",
        "ig": "[i]°g[/i]",
        "ug": "[u]°g[/u]",
        "yg": "[i]°g[/i]",
        "ah": "°H",
        "eh": "[b]°h[/b]",
        "ih": "[i]°h[/i]",
        "uh": "[u]°h[/u]",
        "yh": "[i]°h[/i]",
        "aj": "°J",
        "ej": "[b]°j[/b]",
        "ij": "[i]°j[/i]",
        "uj": "[u]°j[/u]",
        "yj": "[i]°j[/i]",
        "ak": "°K",
        "ek": "[b]°k[/b]",
        "ik": "[i]°k[/i]",
        "uk": "[u]°k[/u]",
        "yk": "[i]°k[/i]",
        "al": "°L",
        "el": "[b]°l[/b]",
        "il": "[i]°l[/i]",
        "ul": "[u]°l[/u]",
        "yl": "[i]°l[/i]",
        "am": "°M",
        "em": "[b]°m[/b]",
        "im": "[i]°m[/i]",
        "um": "[u]°m[/u]",
        "ym": "[i]°m[/i]",
        "an": "°N",
        "en": "[b]°n[/b]",
        "in": "[i]°n[/i]",
        "un": "[u]°n[/u]",
        "yn": "[i]°n[/i]",
        "ap": "°P",
        "ep": "[b]°p[/b]",
        "ip": "[i]°p[/i]",
        "up": "[u]°p[/u]",
        "yp": "[i]°p[/i]",
        "aq": "°Q",
        "eq": "[b]°q[/b]",
        "iq": "[i]°q[/i]",
        "uq": "[u]°q[/u]",
        "yq": "[i]°q[/i]",
        "ar": "°R",
        "er": "[b]°r[/b]",
        "ir": "[i]°r[/i]",
        "ur": "[u]°r[/u]",
        "yr": "[i]°r[/i]",
        "as": "°S",
        "es": "[b]°s[/b]",
        "is": "[i]°s[/i]",
        "us": "[u]°s[/u]",
        "ys": "[i]°s[/i]",
        "at": "°T",
        "et": "[b]°t[/b]",
        "it": "[i]°t[/i]",
        "ut": "[u]°t[/u]",
        "yt": "[i]°t[/i]",
        "av": "°V",
        "ev": "[b]°v[/b]",
        "iv": "[i]°v[/i]",
        "uv": "[u]°v[/u]",
        "yv": "[i]°v[/i]",
        "aw": "°W",
        "ew": "[b]°w[/b]",
        "iw": "[i]°w[/i]",
        "uw": "[u]°w[/u]",
        "yw": "[i]°w[/i]",
        "ax": "°X",
        "ex": "[b]°x[/b]",
        "ix": "[i]°x[/i]",
        "ux": "[u]°x[/u]",
        "yx": "[i]°x[/i]",
        "ay": "°Y",
        "ey": "[b]°y[/b]",
        "iy": "[i]°y[/i]",
        "uy": "[u]°y[/u]",
        "yy": "[i]°y[/i]",
        "az": "°Z",
        "ez": "[b]°z[/b]",
        "iz": "[i]°z[/i]",
        "uz": "[u]°z[/u]",
        "yz": "[i]°z[/i]"}

table4={"ob": "[s]°b[/s]",
        "oc": "[s]°c[/s]",
        "od": "[s]°d[/s]",
        "of": "[s]°f[/s]",
        "og": "[s]°g[/s]",
        "oh": "[s]°h[/s]",
        "oj": "[s]°j[/s]",
        "ok": "[s]°k[/s]",
        "ol": "[s]°l[/s]",
        "om": "[s]°m[/s]",
        "on": "[s]°n[/s]",
        "op": "[s]°p[/s]",
        "oq": "[s]°q[/s]",
        "or": "[s]°r[/s]",
        "os": "[s]°s[/s]",
        "ot": "[s]°t[/s]",
        "ov": "[s]°v[/s]",
        "ow": "[s]°w[/s]",
        "ox": "[s]°x[/s]",
        "oy": "[s]°y[/s]",
        "oz": "[s]°z[/s]"}

table5={"[s]": "[strike]",
        "[/s]": "[/strike]"}

def decode(string):
    string = string.lower()
    brf = []
    nstring = string.split()
    for lstring in nstring:
        for dic in (table1,table2,table3,table4,table5):
            for key in dic.keys():
                if key in lstring:
                    lstring = lstring.replace(key, dic[key])
        brf.append(lstring)
    return " ".join(brf)

def main(argv=[]):
    x = " ".join(argv)
    if len(x) == 0:
        x = input("> ")
    while 1:
        print(decode(x))
        x = input("> ")

if __name__ == "__main__":
    main(sys.argv[1::])
