#!/usr/bin/env python
# -*- coding: utf-8 -*-

# "Standard Abugida"

import sys

rtable = u"[bcdfghjklmnpqrstvwxyz][aeiou]"

table0={u"y": u"i"}

table1={u"ba": u"β",
        u"be": u"[b]b[/b]",
        u"bi": u"[f]b[/f]",
        u"bu": u"[v]b[/v]",
        u"by": u"[f]b[/f]",
        u"ca": u"χ",
        u"ce": u"[b]c[/b]",
        u"ci": u"[f]c[/f]",
        u"cu": u"[v]c[/v]",
        u"cy": u"[f]c[/f]",
        u"da": u"δ",
        u"de": u"[b]d[/b]",
        u"di": u"[f]d[/f]",
        u"du": u"[v]d[/v]",
        u"dy": u"[f]d[/f]",
        u"fa": u"φ",
        u"fe": u"[b]f[/b]",
        u"fi": u"[f]f[/f]",
        u"fu": u"[v]f[/v]",
        u"fy": u"[f]f[/f]",
        u"ga": u"γ",
        u"ge": u"[b]g[/b]",
        u"gi": u"[f]g[/f]",
        u"gu": u"[v]g[/v]",
        u"gy": u"[f]g[/f]",
        u"ha": u"η",
        u"he": u"[b]h[/b]",
        u"hi": u"[f]h[/f]",
        u"hu": u"[v]h[/v]",
        u"hy": u"[f]h[/f]",
        u"ja": u"ϳ",
        u"je": u"[b]j[/b]",
        u"ji": u"[f]j[/f]",
        u"ju": u"[v]j[/v]",
        u"jy": u"[f]j[/f]",
        u"ka": u"κ",
        u"ke": u"[b]k[/b]",
        u"ki": u"[f]k[/f]",
        u"ku": u"[v]k[/v]",
        u"ky": u"[f]k[/f]",
        u"la": u"λ",
        u"le": u"[b]l[/b]",
        u"li": u"[f]l[/f]",
        u"lu": u"[v]l[/v]",
        u"ly": u"[f]l[/f]",
        u"ma": u"μ",
        u"me": u"[b]m[/b]",
        u"mi": u"[f]m[/f]",
        u"mu": u"[v]m[/v]",
        u"my": u"[f]m[/f]",
        u"na": u"ν",
        u"ne": u"[b]n[/b]",
        u"ni": u"[f]n[/f]",
        u"nu": u"[v]n[/v]",
        u"ny": u"[f]n[/f]",
        u"pa": u"π",
        u"pe": u"[b]p[/b]",
        u"pi": u"[f]p[/f]",
        u"pu": u"[v]p[/v]",
        u"py": u"[f]p[/f]",
        u"qa": u"ϟ",
        u"qe": u"[b]q[/b]",
        u"qi": u"[f]q[/f]",
        u"qu": u"[v]q[/v]",
        u"qy": u"[f]q[/f]",
        u"ra": u"ρ",
        u"re": u"[b]r[/b]",
        u"ri": u"[f]r[/f]",
        u"ru": u"[v]r[/v]",
        u"ry": u"[f]r[/f]",
        u"sa": u"σ",
        u"se": u"[b]s[/b]",
        u"si": u"[f]s[/f]",
        u"su": u"[v]s[/v]",
        u"sy": u"[f]s[/f]",
        u"ta": u"τ",
        u"te": u"[b]t[/b]",
        u"ti": u"[f]t[/f]",
        u"tu": u"[v]t[/v]",
        u"ty": u"[f]t[/f]",
        u"va": u"ϐ",
        u"ve": u"[b]v[/b]",
        u"vi": u"[f]v[/f]",
        u"vu": u"[v]v[/v]",
        u"vy": u"[f]v[/f]",
        u"wa": u"ω",
        u"we": u"[b]w[/b]",
        u"wi": u"[f]w[/f]",
        u"wu": u"[v]w[/v]",
        u"wy": u"[f]w[/f]",
        u"xa": u"ξ",
        u"xe": u"[b]x[/b]",
        u"xi": u"[f]x[/f]",
        u"xu": u"[v]x[/v]",
        u"xy": u"[f]x[/f]",
        u"ya": u"ψ",
        u"ye": u"[b]y[/b]",
        u"yi": u"[f]y[/f]",
        u"yu": u"[v]y[/v]",
        u"yy": u"[f]y[/f]",
        u"za": u"ζ",
        u"ze": u"[b]z[/b]",
        u"zi": u"[f]z[/f]",
        u"zu": u"[v]z[/v]",
        u"zy": u"[f]z[/f]"}

table2={u"bo": u"[s]b[/s]",
        u"co": u"[s]c[/s]",
        u"do": u"[s]d[/s]",
        u"fo": u"[s]f[/s]",
        u"go": u"[s]g[/s]",
        u"ho": u"[s]h[/s]",
        u"jo": u"[s]j[/s]",
        u"ko": u"[s]k[/s]",
        u"lo": u"[s]l[/s]",
        u"mo": u"[s]m[/s]",
        u"no": u"[s]n[/s]",
        u"po": u"[s]p[/s]",
        u"qo": u"[s]q[/s]",
        u"ro": u"[s]r[/s]",
        u"so": u"[s]s[/s]",
        u"to": u"[s]t[/s]",
        u"vo": u"[s]v[/s]",
        u"wo": u"[s]w[/s]",
        u"xo": u"[s]x[/s]",
        u"yo": u"[s]y[/s]",
        u"zo": u"[s]z[/s]"}

table3={u"ab": u"°β",
        u"eb": u"[b]°b[/b]",
        u"ib": u"[f]°b[/f]",
        u"ub": u"[v]°b[/v]",
        u"yb": u"[f]°b[/f]",
        u"ac": u"°χ",
        u"ec": u"[b]°c[/b]",
        u"ic": u"[f]°c[/f]",
        u"uc": u"[v]°c[/v]",
        u"yc": u"[f]°c[/f]",
        u"ad": u"°δ",
        u"ed": u"[b]°d[/b]",
        u"id": u"[f]°d[/f]",
        u"ud": u"[v]°d[/v]",
        u"yd": u"[f]°d[/f]",
        u"af": u"°φ",
        u"ef": u"[b]°f[/b]",
        u"if": u"[f]°f[/f]",
        u"uf": u"[v]°f[/v]",
        u"yf": u"[f]°f[/f]",
        u"ag": u"°γ",
        u"eg": u"[b]°g[/b]",
        u"ig": u"[f]°g[/f]",
        u"ug": u"[v]°g[/v]",
        u"yg": u"[f]°g[/f]",
        u"ah": u"°η",
        u"eh": u"[b]°h[/b]",
        u"ih": u"[f]°h[/f]",
        u"uh": u"[v]°h[/v]",
        u"yh": u"[f]°h[/f]",
        u"aj": u"°ϳ",
        u"ej": u"[b]°j[/b]",
        u"ij": u"[f]°j[/f]",
        u"uj": u"[v]°j[/v]",
        u"yj": u"[f]°j[/f]",
        u"ak": u"°κ",
        u"ek": u"[b]°k[/b]",
        u"ik": u"[f]°k[/f]",
        u"uk": u"[v]°k[/v]",
        u"yk": u"[f]°k[/f]",
        u"al": u"°λ",
        u"el": u"[b]°l[/b]",
        u"il": u"[f]°l[/f]",
        u"ul": u"[v]°l[/v]",
        u"yl": u"[f]°l[/f]",
        u"am": u"°μ",
        u"em": u"[b]°m[/b]",
        u"im": u"[f]°m[/f]",
        u"um": u"[v]°m[/v]",
        u"ym": u"[f]°m[/f]",
        u"an": u"°ν",
        u"en": u"[b]°n[/b]",
        u"in": u"[f]°n[/f]",
        u"un": u"[v]°n[/v]",
        u"yn": u"[f]°n[/f]",
        u"ap": u"°π",
        u"ep": u"[b]°p[/b]",
        u"ip": u"[f]°p[/f]",
        u"up": u"[v]°p[/v]",
        u"yp": u"[f]°p[/f]",
        u"aq": u"°ϟ",
        u"eq": u"[b]°q[/b]",
        u"iq": u"[f]°q[/f]",
        u"uq": u"[v]°q[/v]",
        u"yq": u"[f]°q[/f]",
        u"ar": u"°ρ",
        u"er": u"[b]°r[/b]",
        u"ir": u"[f]°r[/f]",
        u"ur": u"[v]°r[/v]",
        u"yr": u"[f]°r[/f]",
        u"as": u"°σ",
        u"es": u"[b]°s[/b]",
        u"is": u"[f]°s[/f]",
        u"us": u"[v]°s[/v]",
        u"ys": u"[f]°s[/f]",
        u"at": u"°τ",
        u"et": u"[b]°t[/b]",
        u"it": u"[f]°t[/f]",
        u"ut": u"[v]°t[/v]",
        u"yt": u"[f]°t[/f]",
        u"av": u"°ϐ",
        u"ev": u"[b]°v[/b]",
        u"iv": u"[f]°v[/f]",
        u"uv": u"[v]°v[/v]",
        u"yv": u"[f]°v[/f]",
        u"aw": u"°ω",
        u"ew": u"[b]°w[/b]",
        u"iw": u"[f]°w[/f]",
        u"uw": u"[v]°w[/v]",
        u"yw": u"[f]°w[/f]",
        u"ax": u"°ξ",
        u"ex": u"[b]°x[/b]",
        u"ix": u"[f]°x[/f]",
        u"ux": u"[v]°x[/v]",
        u"yx": u"[f]°x[/f]",
        u"ay": u"°ψ",
        u"ey": u"[b]°y[/b]",
        u"iy": u"[f]°y[/f]",
        u"uy": u"[v]°y[/v]",
        u"yy": u"[f]°y[/f]",
        u"az": u"°ζ",
        u"ez": u"[b]°z[/b]",
        u"iz": u"[f]°z[/f]",
        u"uz": u"[v]°z[/v]",
        u"yz": u"[f]°z[/f]"}

table4={u"ob": u"[s]°b[/s]",
        u"oc": u"[s]°c[/s]",
        u"od": u"[s]°d[/s]",
        u"of": u"[s]°f[/s]",
        u"og": u"[s]°g[/s]",
        u"oh": u"[s]°h[/s]",
        u"oj": u"[s]°j[/s]",
        u"ok": u"[s]°k[/s]",
        u"ol": u"[s]°l[/s]",
        u"om": u"[s]°m[/s]",
        u"on": u"[s]°n[/s]",
        u"op": u"[s]°p[/s]",
        u"oq": u"[s]°q[/s]",
        u"or": u"[s]°r[/s]",
        u"os": u"[s]°s[/s]",
        u"ot": u"[s]°t[/s]",
        u"ov": u"[s]°v[/s]",
        u"ow": u"[s]°w[/s]",
        u"ox": u"[s]°x[/s]",
        u"oy": u"[s]°y[/s]",
        u"oz": u"[s]°z[/s]"}

table5={u"a": u"α",
        u"e": u"ε",
        u"i": u"ι",
        u"o": u"ο",
        u"u": u"υ"}

table6={u"[s]": u"[strike]",
        u"[/s]": u"[/strike]",
        u"[f]": u"[i]",
        u"[/f]": u"[/i]",
        u"[v]": u"[u]",
        u"[/v]": u"[/u]"}

table7=[u"B", u"C", u"D", u"F", u"G", u"H", u"J", u"K", u"L", u"M", u"N", u"P", u"Q", u"R", u"S", u"T", u"V", u"W", u"X", u"Y", u"Z"]

def decode(string):
    brf = []
    nstring = string.split()
    for lstring in nstring:
        for dic in (table0,table1,table2,table3,table4,table5,table6,table7):
            if type(dic) is list:
                for char in dic:
                    lstring = lstring.replace(char, u"↑" + char.lower())
            else:
                for key in dic.keys():
                    if key in lstring:
                        lstring = lstring.replace(key, dic[key])
                    if key.capitalize() in lstring:
                        r = dic[key]
                        if u"[/" in r:
                            lstring = lstring.replace(key.capitalize(), r.replace(u"]", u"]↑", 1))
                        else:
                            lstring = lstring.replace(key.capitalize(), u"↑" + r)
        brf.append(lstring)
    return u" ".join(brf)

def main(argv=[]):
    print "Standard Abugida Converter (Python %s)" % (sys.version,)
    x = u" ".join(argv)
    if len(x) == 0:
        x = raw_input(u">>> ")
    while 1:
        print decode(x)
        x = raw_input(u">>> ")

if __name__ == u"__main__":
    main(sys.argv[1::])
